name: deploying-voila-notebook
channels:
  - conda-forge
dependencies:
  - matplotlib-base
  - pandas
  - ipywidgets=7.7
  - voila
  - numpy
  - nb_conda_kernels
  - jupyterlab_widgets
  - nbformat
  - jupyter_server
  - jupyter_client
  - nbconvert
  - notebook
  - ipykernel
  - python=3
  - pip
  - pip:
    - voila-vuetify

