name: deploying-voila-notebook
channels:
  - conda-forge
dependencies:
  - matplotlib-base
  - pandas
  - ipywidgets
  - jupyterlab>=3.1
  - voila>=0.2.11
  - numpy
  - nb_conda_kernels
  - nodejs
  - jupyterlab_widgets
  - nbformat
  - jupyter_server
  - jupyter_client
  - nbconvert
  - notebook
  - ipykernel
  - nb_conda
  - python=3
  - pip
  - pip:
    - voila-vuetify

